twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        test_data: '%env(test_data)%'
        adm_img_carousel_path: '%env(ADM_IMG_CAROUSEL_PATH)%'
        adm_url: '%env(ADM_URL)%'

when@test:
    twig:
        strict_variables: true
