test:
  path: /test
  controller: App\Controller\ContentController::buildTest

test.auth:
  path: /test_auth
  controller: App\Controller\ContentController::testAuth

test.userdata:
  path: /test_userdata
  controller: App\Controller\ContentController::buildTestUserData

login:
  path: /login
  controller: App\Controller\ContentController::buildLogin

signup:
  path: /signup
  controller: App\Controller\ContentController::buildSignUp  

# index:
#   path: /index
#   controller: App\Controller\ContentController::buildIndex

reg.apply.add:
  path: /regapply/{aircraftId}
  controller: App\Controller\ContentController::buildRegApplyAdd

uav:
  path: /uav
  controller: App\Controller\ContentController::buildUav

uav.pages:
  path: /uav/{page}
  controller: App\Controller\ContentController::buildUavPaginated

profile:
  path: /profile
  controller: App\Controller\ContentController::buildProfile

form_js:
  path: /javascript/forms.js
  controller: App\Controller\ContentController::buildFormJs

reg_apply:
  path: /javascript/reg_apply.js
  controller: App\Controller\ContentController::buildRegApplyJs

#content:
#  path: /{route}
#  controller: App\Controller\ContentController::buildContent
#  requirements:
#    route: '.*'


